# Use postgres/example user/password credentials
version: "3.7"

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tiendalibroautor
    ports:
      - 5432:5432
  
  # rabbit:
  #   image: rabbitmq:3.8-rc-management-alpine
  #   restart: always
  #   hostname: my-rabbit
  #   environment:
  #     RABBITMQ_DEFAULT_PASS: password
  #     RABBITMQ_DEFAULT_USER: user
  #   ports:
  #     - 5672:5672
  #     - 15672:15672 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8989:8080

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      # - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    volumes:
      - elasticsearch-data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      # - elasticsearch.username=kibana
      # - elasticsearch.userpassword=tj5ZI7Tbi4vCg3VoQ2Z3
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: