# Use postgres/example user/password credentials
version: "3.7"

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tiendalibroautor
    ports:
      - 5432:5432
  
  # rabbit:
  #   image: rabbitmq:3.8-rc-management-alpine
  #   restart: always
  #   hostname: my-rabbit
  #   environment:
  #     RABBITMQ_DEFAULT_PASS: password
  #     RABBITMQ_DEFAULT_USER: user
  #   ports:
  #     - 5672:5672
  #     - 15672:15672 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8989:8080
